# Generated by Django 3.1.2 on 2020-10-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='middle name'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('Учитель', 'Учитель'), ('Ученик', 'Ученик')], default='football', max_length=255, verbose_name='Status'),
        ),
    ]
