# Generated by Django 3.1.2 on 2020-10-28 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(verbose_name='Статус')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Учащиеся')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.task', verbose_name='Задание')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(through='main_app.TaskDetail', to=settings.AUTH_USER_MODEL, verbose_name='Учащиеся'),
        ),
    ]
