# Generated by Django 3.1.2 on 2020-10-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201028_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mission',
            field=models.CharField(blank=True, max_length=30, verbose_name='Техническое задание'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название спринта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='theory',
            field=models.CharField(blank=True, max_length=30, verbose_name='Теоретическое введение'),
        ),
    ]
