# Generated by Django 3.1.2 on 2020-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201027_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='Alpine12', max_length=128, verbose_name='password'),
        ),
    ]
