# Generated by Django 3.1.2 on 2020-10-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201028_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='last_code',
            field=models.CharField(blank=True, max_length=300, verbose_name='Последний запущенный код'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Учащийся'),
        ),
    ]
