# Generated by Django 3.1.2 on 2020-10-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201028_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprints', to='main_app.grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='main_app.sprint'),
        ),
    ]
