# Generated by Django 3.1.2 on 2020-10-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201028_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_detail', to='main_app.task', verbose_name='Задание'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='Входные данные')),
                ('answer', models.TextField(blank=True, verbose_name='Выходные данные')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test', to='main_app.task', verbose_name='Тест')),
            ],
        ),
    ]
