# Generated by Django 3.1.2 on 2020-10-28 22:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201029_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('c_sharp', 'C#'), ('pascal', 'Pascal')], default='python', max_length=30),
        ),
    ]
