# Generated by Django 3.1.2 on 2020-10-29 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_task_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
