# Generated by Django 3.1.2 on 2020-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201029_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
