# Generated by Django 3.1.2 on 2020-10-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201027_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='class name')),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.grade')),
            ],
        ),
    ]
