# Generated by Django 3.1.2 on 2020-10-30 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20201030_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='main_app.grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main_app.sprint'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учащийся'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_detail', to='main_app.task', verbose_name='Задание'),
        ),
    ]
