# Generated by Django 3.1.2 on 2020-10-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='sprint name'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='task name')),
                ('theory', models.CharField(blank=True, max_length=30, verbose_name='theory content')),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='task name')),
                ('theory', models.CharField(blank=True, max_length=30, verbose_name='theory content')),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.grade')),
            ],
        ),
    ]
