# Generated by Django 3.1.2 on 2020-10-30 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20201030_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='users',
        ),
        migrations.AddField(
            model_name='grade',
            name='grades',
            field=models.ManyToManyField(related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
