# Generated by Django 3.1.2 on 2020-10-27 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20201027_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
