# Generated by Django 3.1.2 on 2020-10-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20201030_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название класса'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название спринта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='mission',
            field=models.TextField(blank=True, max_length=64, verbose_name='Техническое задание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='theory',
            field=models.TextField(blank=True, verbose_name='Теоретическое введение'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='last_code',
            field=models.TextField(blank=True, verbose_name='Последний запущенный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='middle name'),
        ),
    ]
