# Generated by Django 3.1.2 on 2020-10-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20201027_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='teacher',
            new_name='users',
        ),
    ]
