# Generated by Django 3.1.2 on 2020-10-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20201031_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='main_app.task', verbose_name='Тест'),
        ),
    ]
