# Generated by Django 3.1.2 on 2020-10-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20201031_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=64, verbose_name='middle name'),
        ),
    ]
